#!/bin/sh

ZWACONF=./.zwaconf

TARGET=

set -e

if [ -f $ZWACONF ]; then
  . $ZWACONF
fi

if [ -z "$TARGET" ]; then
  TARGET=$PWD/out
fi

get_version(){
      head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
}

sed_file() {

    while [ -n "$1" ]; do
        in=$1.in
        out=$1

        sed \
            -e "s,@TARGET@,${TARGET},g" \
            -e "s/@VERSION@/${VERSION}/g" \
            $in > $out
        shift
    done
}

CFLAGS="--cccl-die-unsupported /O2 /W3 -q /MD "
DEFS="-D_WIN32 -D_UNICODE -DUNICODE -g -D_WIN32_WINNT=0x0500 -DHAVE_STRING_H -DSTDC_HEADERS -DHAVE_ALLOCA_H"
LDFLAGS="-g -Wl,/OPT:REF,/OPT:ICF"

export CFLAGS DEFS LDFLAGS
cmd=$1

shift
case "$cmd" in
  get-version)
    get_version
    ;;
  prepare-dist)
    VERSION=`get_version`
    ;;
  dist-exclude-list|build-exclude-list)
    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ;;
  bootstrap)
    ;;
  configure)
    OPTIONS=`getopt -l help,prefix: 'p:' $*`
    if [ $? -ne 0 ]; then
      echo "$0: unknown flags..."
      exit 1
    fi

    eval set -- "$OPTIONS"
    while true ; do
      _arg=$1

      if [ -z "$_arg" ]; then
        break
      fi
      case $1 in
        --prefix|-p)
          shift
          TARGET=`cygpath -u "$1"`
          ;;
      esac
      shift
    done
    echo "TARGET=$TARGET" > $ZWACONF
    set -x
    CC=cccl LD=cccl CXX=cccl \
    ./configure --prefix=/ 
    ;;
  make)
    if [ -z "$1" ]; then
      # need to do this way, otherwise po-properties' make kills libtool. dang.
      if [ -f config.status ]; then
        touch config.status
        $SHELL ./config.status
      fi
      make
      lib /out:regex.lib regex.obj alloca.obj
    else
      case $1 in
        clean)
          make clean
          /usr/bin/find . -name \*.obj -or -name \*.dll -or -name \*.map -or -name \*.manifest -or -name \*.pdb -o -name \*.exp -o -name \*ilk -o -name \*.idb -o -name \*.lib | xargs -r rm -f
          ;;
        install)
          mkdir -p $TARGET/include $TARGET/lib
          install -v regex.h $TARGET/include
          install -v regex.lib regex.obj $TARGET/lib
          ;;
      esac
    fi
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
