#!/bin/sh -ex

ZWACONF=.zwaconf

TARGET=

if [ -f $ZWACONF ]; then
  . ./$ZWACONF
fi

ubuild=./balabit-unix-build

if [ -z "$TARGET" ]; then
  TARGET=$PWD/out
fi

sed_file() {

    while [ -n "$1" ]; do
        in=$1.in
        out=$1

        sed \
            -e "s,@TARGET@,${TARGET},g" \
            -e "s/@VERSION@/${VERSION}/g" \
            $in > $out
        shift
    done
}

cmd=$1

shift
case "$cmd" in
  get-version)
    get_version
    ;;
  prepare-dist)
    VERSION=`get_version`
    sed_file winbuild/build.bat
    ;;
  dist-exclude-list|build-exclude-list)
    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ;;
  bootstrap)
    $ubuild bootstrap $@
    ;;
  configure)
    $ubuild configure $@
    ;;
  make)
    $ubuild make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
