name: regex
builder:
  name: BalabitBuilder
  flags: "no-local-build no-configure no-make-dist"
platforms:
  - aix-6.1/powerpc
  - freebsd-9.2/amd64
  - freebsd-9.2/i386
  - freebsd-10.1/amd64
  - hpux-11v2/ia64
  - linux-glibc2.11/amd64
  - linux-glibc2.11/i386
  - linux-glibc2.3.6/amd64
  - linux-glibc2.3.6/i386
  - solaris-10/amd64
  - solaris-10/sparc
  - solaris-10/sparc64
  - solaris-11/amd64
  - solaris-11/sparc64
  - windows-2012/amd64
  - windows-2012/i386
  - ubuntu-bionic/amd64
